### ISSUE TITLE
请问下大大 Cygwin 可以安装ffi吗？

### ISSUE THREAD

**Issue by xu767142206** [jingjingxyk/swoole-cli#73]
我在./configure 命令上增加 --with-ffi 他提示我命令不存在

**Comment by jingjingxyk** [comment]
先来这里搜索libffi 库   https://cygwin.com/cgi-bin2/package-grep.cgi?grep=libffi

然后安装 libffi 库 如下
```shell

setup-x86_64.exe  --no-desktop --no-shortcuts --no-startmenu --quiet-mode    --site  http://mirrors.ustc.edu.cn/cygwin/ --packages libffi-devel

```

更多帮助信息： 
cygwin 搜索包：    https://cygwin.com/cgi-bin2/package-grep.cgi?grep=libffi 
 
构建选项： https://github.com/swoole/swoole-cli/blob/main/docs/Cygwin.md
cygwin 构建脚本 https://github.com/swoole/swoole-cli/tree/experiment/sapi/scripts/cygwin

**Comment by jingjingxyk** [comment]
或者使用 build_native_php 分支也行 (此分支使用php 源码构建） ；swoole-cli 是在php 源码基础上做了相应功能的裁剪
```shell

git clone -b build_native_php  https://github.com/swoole/swoole-cli.git

```

**Comment by xu767142206** [comment]
> 或者使用 build_native_php 分支也行 (此分支使用php 源码构建） ；
> 
> ```shell
> git clone -b build_native_php  https://github.com/swoole/swoole-cli.git
> ```
> 
> swoole-cli 是在php 源码基础上做了相应功能的裁剪，因此不包含ffi 扩展

谢谢大大

**Comment by xu767142206** [comment]
![image](https://github.com/jingjingxyk/swoole-cli/assets/44433417/34cef61a-5fd5-46d6-a3fd-d216d899ea8f)
已经可以了 谢谢大大
